FROM node:12.13.0-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app
COPY . /home/node/app
RUN npm install -g yarn
RUN npm install -g nest
RUN yarn install
USER node
COPY --chown=node:node . .
EXPOSE 5000
CMD [ "npm", "start" ,"api"]

