version: "3"
services:
  redis_db:
    image: redis
    container_name: cache
    expose:
      - "6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis_db

  movieDb:
    image: "postgres"
    container_name: "movie_postgres"
    environment:
      - POSTGRES_USER=sanjeev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=movies
    ports:
      - "54320:5432"
    volumes:
      - ~/postgres-movies:/var/lib/postgresql/data

  genreDb:
    image: "postgres"
    container_name: "genre_postgres"
    environment:
      - POSTGRES_USER=sanjeev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=genres
    ports:
      - "54321:5432"
    volumes:
      - ~/postgres-genres:/var/lib/postgresql/data

  movies:
    build:
      context: .
      dockerfile: Dockerfile.movies
    links:
      - redis_db
      - movieDb
      - genreDb
    environment:
      - REDIS_URL=redis://redis_db:6379
      - MOVIES_DB_URL=postgres://sanjeev:password@movieDb:5432/movies
    depends_on:
      - redis_db
      - movieDb
  genres:
    build:
      context: .
      dockerfile: Dockerfile.genres
    links:
      - redis_db
      - genreDb
    environment:
      - REDIS_URL=redis://redis_db:6379
      - GENRES_DB_URL=postgres://sanjeev:password@genreDb:5432/genres
      - NODE_ENV=development
    depends_on:
      - redis_db
      - genreDb
  api:
    build:
      context: .
      dockerfile: Dockerfile.web
    links:
      - redis_db
      - movieDb
      - genreDb
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis_db:6379
      - MOVIES_DB_URL=postgres://sanjeev:password@movieDb:5432/movies
      - GENRES_DB_URL=postgres://sanjeev:password@genreDb:5432/genres
      - PORT=5000
    depends_on:
      - redis_db
      - movieDb
      - genreDb
      - movies
      - genres
