FROM node:12.13.0-alpine
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY ./package.json /home/node/app
COPY ./dist /home/node/app/dist
COPY ./yarn.lock /home/node/app
RUN npm install -g yarn
RUN yarn install --prod
USER node
COPY --chown=node:node . .
CMD [ "node", "dist/apps/genres/main.js"]

